---

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy artifact
  template:
    src: "~/project/artifact.tar.gz"
    dest: "~/web/"

- name: "Extract artifact"
  shell: | 
    tar -xzvf artifact.tar.gz ~/web/

- name: Executing node
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start