---

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy artifact
  template:
    src: "files/artifact.tar.gz"
    dest: "~/"

- name: "Extract artifact"
  shell: | 
    tar -xzf artifact.tar.gz ~/web/

- name: Executing node
  shell: |
    cd ~/web/
    npm install
    pm2 stop default
    pm2 start npm -- start